package com.vilp.notification.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.io.IOException;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Server-Sent Events endpoint for real-time push notifications.
 * Clients connect via GET /api/notifications/stream and receive events
 * as they are generated by domain services.
 *
 * SSE is simpler than WebSocket (unidirectional, HTTP-based, auto-reconnect)
 * and works on Render free tier without sticky sessions.
 */
@RestController
@RequestMapping("/api/notifications/stream")
@SecurityRequirement(name = "Bearer Authentication")
@Tag(name = "Real-Time Notifications", description = "SSE stream for push notifications")
@Slf4j
public class SseNotificationController {

    private final ConcurrentHashMap<UUID, SseEmitter> emitters = new ConcurrentHashMap<>();

    @GetMapping(produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    @PreAuthorize("isAuthenticated()")
    @Operation(summary = "Subscribe to real-time notification stream")
    public SseEmitter subscribe(@AuthenticationPrincipal UserDetails ud) {
        UUID userId = UUID.fromString(ud.getUsername());

        // 30-minute timeout (matches access token lifetime)
        SseEmitter emitter = new SseEmitter(30 * 60 * 1000L);

        emitters.put(userId, emitter);
        emitter.onCompletion(() -> {
            emitters.remove(userId);
            log.debug("SSE connection closed for user {}", userId);
        });
        emitter.onTimeout(() -> {
            emitters.remove(userId);
            log.debug("SSE connection timed out for user {}", userId);
        });
        emitter.onError(e -> {
            emitters.remove(userId);
            log.debug("SSE connection error for user {}: {}", userId, e.getMessage());
        });

        // Send initial heartbeat so client knows connection is alive
        try {
            emitter.send(SseEmitter.event().name("connected").data("ok"));
        } catch (IOException e) {
            emitters.remove(userId);
        }

        log.debug("SSE connection established for user {}", userId);
        return emitter;
    }

    /**
     * Push a notification event to a specific user if they are connected.
     * Called by NotificationService after creating a notification.
     * Fails silently if user is not connected — they'll see it on next poll.
     */
    public void pushToUser(UUID userId, Object notification) {
        SseEmitter emitter = emitters.get(userId);
        if (emitter != null) {
            try {
                emitter.send(SseEmitter.event()
                        .name("notification")
                        .data(notification, MediaType.APPLICATION_JSON));
            } catch (IOException e) {
                emitters.remove(userId);
                log.debug("Failed to push SSE to user {}, removing emitter", userId);
            }
        }
    }

    /** Get count of currently connected users (for admin monitoring) */
    public int getConnectedUserCount() {
        return emitters.size();
    }
}
